version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15.1-browsers
        environment:
          NO_SANDBOX: true
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: build-docs
          command: npm run docs:build
      - persist_to_workspace:
          root: .
          paths:
            - ./docs/.vuepress/dist

  deploy:
    docker:
      - image: olizilla/ipfs-dns-deploy:debug
        environment:
          DOMAIN: docs.ipfs.io
          BUILD_DIR: ./docs/.vuepress/dist
          CLUSTER_HOST: /dnsaddr/ipfs-websites.collab.ipfscluster.io
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Deploy website to IPFS
          command: |
            pin_name="$DOMAIN build $CIRCLE_BUILD_NUMBER"
            
            hash=$(pin-to-cluster.sh "$pin_name" /tmp/workspace/$BUILD_DIR)
            echo "Website added to IPFS: https://ipfs.io/ipfs/$hash"
            # Update DNSlink for prod
            if [ "$CIRCLE_BRANCH" == "main" ] ; then
              dnslink-dnsimple -d $DOMAIN -r _dnslink -l /ipfs/$hash
              export CLUSTER_HOST=/dnsaddr/ipfs-websites.collab.ipfscluster.io
              pin-to-cluster.sh "$DOMAIN" /tmp/workspace/$BUILD_DIR
              echo "Website added to collaborative cluster"
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          context: ipfs-dns-deploy
          requires:
            - build
